"""
Gamma Strategy (Whale Execution Logic) - Task 22
=================================================

Isolated execution logic for CONVEXITY_OPPORTUNITY regime.
Targets "Out of the Money" (OTM) options priced between $0.01-$0.10.

Strategy Overview:
- Accumulate cheap exposure via Maker orders (joining the bid)
- Selective Taker orders (sniping weak walls)
- Sell into volatility spikes ("Free Roll" exits)

This file does NOT predict winners; it identifies mispriced convexity.

IMPORTANT: This module is ISOLATED and must NOT modify or impact:
- hft_strategy.py
- alpha_model.py
- Any existing trading logic

Author: Task 22 Implementation
Date: January 26, 2026
"""

import logging
from typing import Dict, List, Optional, Tuple
from dataclasses import dataclass, field
from enum import Enum
from datetime import datetime, timezone

from risk_config import RISK, RiskConfig

logger = logging.getLogger(__name__)


# =============================================================================
# DATA STRUCTURES
# =============================================================================

class GammaOrderType(Enum):
    """Order type for Gamma strategy."""
    LIMIT_BID = "limit_bid"      # Join the bid queue (maker)
    LIMIT_ASK = "limit_ask"      # Join the ask queue (maker)
    MARKET_BUY = "market_buy"    # Snipe weak wall (taker)
    MARKET_SELL = "market_sell"  # Exit position (taker)


class GammaOrderReason(Enum):
    """Reason for generating an order."""
    # Entry reasons
    GAP_OPPORTUNITY = "gap_opportunity"       # Wide gap, place bid inside
    WALL_CRUMBLING = "wall_crumbling"         # Weak ask wall, snipe it
    WALL_STRONG = "wall_strong"               # Strong wall, join bid
    
    # Exit reasons
    FREE_ROLL = "free_roll"                   # 2x entry, sell 50%
    MOONBAG = "moonbag"                       # 5x entry, sell remainder
    STOP_LOSS = "stop_loss"                   # 0.5x entry, cut losses


@dataclass
class GammaOrder:
    """
    Order generated by Gamma strategy.
    
    This is a "signal" that gets passed to the execution layer.
    The execution layer decides how to actually execute it.
    """
    market_id: str
    token_id: str
    side: str                     # 'YES' or 'NO'
    order_type: GammaOrderType
    price: float                  # Limit price (for limit orders) or expected price (for market)
    size: float                   # Size in USD
    reason: GammaOrderReason
    
    # Metadata for tracking
    entry_price: Optional[float] = None  # For exits, the original entry price
    position_id: Optional[str] = None    # For exits, link to position
    
    # Orderbook context (for logging/debugging)
    best_bid: float = 0.0
    best_ask: float = 0.0
    bid_volume: float = 0.0
    ask_volume: float = 0.0
    
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    
    def to_dict(self) -> Dict:
        """Convert to dictionary for JSON serialization."""
        return {
            'market_id': self.market_id,
            'token_id': self.token_id,
            'side': self.side,
            'order_type': self.order_type.value,
            'price': self.price,
            'size': self.size,
            'reason': self.reason.value,
            'entry_price': self.entry_price,
            'position_id': self.position_id,
            'best_bid': self.best_bid,
            'best_ask': self.best_ask,
            'bid_volume': self.bid_volume,
            'ask_volume': self.ask_volume,
            'timestamp': self.timestamp.isoformat(),
        }


# =============================================================================
# GAMMA TRADER CLASS
# =============================================================================

class GammaTrader:
    """
    Gamma Strategy Executor for Whale Zone (CONVEXITY_OPPORTUNITY regime).
    
    This class does NOT predict winners; it identifies mispriced convexity.
    
    Entry Logic ("Gap vs. Wall"):
    - Gap: Wide spread → place limit bid inside the gap
    - Wall: Tight spread → snipe weak wall OR join strong bid
    
    Exit Logic ("Free Roll"):
    - 2x Entry: Sell 50% (Free Roll)
    - 5x Entry: Sell 100% (Moonbag)
    - 0.5x Entry: Sell 100% (Stop Loss)
    
    ISOLATED: This class has no dependencies on HFT or Alpha logic.
    """
    
    def __init__(self, config: Optional[RiskConfig] = None):
        """
        Initialize Gamma Trader.
        
        Args:
            config: Risk configuration. Uses global RISK if not provided.
        """
        self.config = config or RISK
        
        # Statistics for monitoring
        self.stats = {
            'orders_generated': 0,
            'gap_opportunities': 0,
            'wall_snipes': 0,
            'wall_joins': 0,
            'free_rolls': 0,
            'moonbags': 0,
            'stop_losses': 0,
            'skipped_expensive': 0,
            'skipped_max_position': 0,
        }
        
        logger.info("🐋 GammaTrader initialized (Whale Strategy)")
    
    # =========================================================================
    # ENTRY LOGIC: calculate_orders()
    # =========================================================================
    
    def calculate_orders(
        self,
        market_data: Dict,
        active_positions: Dict[str, Dict],
        available_capital: float = 1000.0
    ) -> List[GammaOrder]:
        """
        Calculate entry orders for a market in CONVEXITY_OPPORTUNITY regime.
        
        This method implements the "Gap vs. Wall" logic:
        - Gap: Place limit bid inside wide spreads
        - Wall: Snipe weak walls or join strong bids
        
        Args:
            market_data: Market data including orderbook
            active_positions: Dict of market_id -> position data
            available_capital: Capital available for new trades
            
        Returns:
            List of GammaOrder objects (may be empty if no opportunity)
        """
        orders = []
        
        market_id = market_data.get('id', '')
        
        # Extract YES and NO prices
        yes_price = float(market_data.get('yes_price', 0) or 0)
        no_price = float(market_data.get('no_price', 1 - yes_price) or (1 - yes_price))
        
        # Get orderbook data
        order_book = market_data.get('order_book', {})
        bids = order_book.get('bids', [])
        asks = order_book.get('asks', [])
        
        if not bids or not asks:
            logger.debug(f"[GAMMA] {market_id[:16]}... No orderbook data")
            return orders
        
        best_bid = float(bids[0].get('price', 0))
        best_ask = float(asks[0].get('price', 1))
        
        # Calculate volumes
        bid_volume = sum(float(b.get('size', 0)) for b in bids[:3])  # Top 3 levels
        ask_volume = sum(float(a.get('size', 0)) for a in asks[:3])
        
        # =====================================================================
        # STEP 1: Side Selection - Which side is the "Whale" side?
        # =====================================================================
        whale_side, whale_price = self._identify_whale_side(yes_price, no_price)
        
        if whale_side is None:
            # Both sides are expensive (> $0.10), no whale opportunity
            self.stats['skipped_expensive'] += 1
            logger.debug(f"[GAMMA] {market_id[:16]}... Both sides expensive (YES={yes_price:.4f}, NO={no_price:.4f})")
            return orders
        
        # =====================================================================
        # STEP 2: Check if we've hit max position for this token
        # =====================================================================
        existing_exposure = self._calculate_existing_exposure(market_id, whale_side, active_positions)
        
        if existing_exposure >= self.config.WHALE_MAX_POSITION:
            self.stats['skipped_max_position'] += 1
            logger.debug(f"[GAMMA] {market_id[:16]}... Max position reached (${existing_exposure:.2f} >= ${self.config.WHALE_MAX_POSITION})")
            return orders
        
        # Calculate available size for this trade
        remaining_capacity = self.config.WHALE_MAX_POSITION - existing_exposure
        position_size = min(
            remaining_capacity,
            self.config.WHALE_MAX_POSITION,
            available_capital * (self.config.WHALE_MAX_POSITION_PCT / 100)
        )
        
        if position_size < 5.0:  # Minimum $5 trade
            logger.debug(f"[GAMMA] {market_id[:16]}... Position size too small (${position_size:.2f})")
            return orders
        
        # =====================================================================
        # STEP 3: Spread Evaluation - "Gap vs. Wall" Logic
        # =====================================================================
        spread_cents = best_ask - best_bid
        token_id = market_data.get('clobTokenIds', [''])[0] if whale_side == 'YES' else market_data.get('clobTokenIds', ['', ''])[1] if len(market_data.get('clobTokenIds', [])) > 1 else ''
        
        order = self._evaluate_spread(
            market_id=market_id,
            token_id=token_id,
            side=whale_side,
            best_bid=best_bid,
            best_ask=best_ask,
            bid_volume=bid_volume,
            ask_volume=ask_volume,
            spread_cents=spread_cents,
            position_size=position_size
        )
        
        if order:
            orders.append(order)
            self.stats['orders_generated'] += 1
            logger.info(
                f"🐋 [GAMMA ENTRY] {market_id[:16]}... {order.side} @ ${order.price:.4f} "
                f"(Size: ${order.size:.2f}, Reason: {order.reason.value})"
            )
        
        return orders
    
    def _identify_whale_side(self, yes_price: float, no_price: float) -> Tuple[Optional[str], float]:
        """
        Identify which side (YES/NO) is the "Whale" side.
        
        The Whale side is the cheap side (< WHALE_PRICE_CEILING).
        
        Args:
            yes_price: Current YES price
            no_price: Current NO price (1 - yes_price typically)
            
        Returns:
            Tuple of (side, price) or (None, 0) if no whale opportunity
        """
        ceiling = self.config.WHALE_PRICE_CEILING
        floor = self.config.KILL_SWITCH_LOW
        
        # Check YES side
        yes_is_whale = floor <= yes_price < ceiling
        
        # Check NO side
        no_is_whale = floor <= no_price < ceiling
        
        # If both are whale zone, prefer the cheaper one
        if yes_is_whale and no_is_whale:
            if yes_price <= no_price:
                return 'YES', yes_price
            else:
                return 'NO', no_price
        
        # If only one is whale zone
        if yes_is_whale:
            return 'YES', yes_price
        if no_is_whale:
            return 'NO', no_price
        
        # Neither side is in whale zone
        return None, 0.0
    
    def _calculate_existing_exposure(
        self,
        market_id: str,
        side: str,
        active_positions: Dict[str, Dict]
    ) -> float:
        """
        Calculate existing exposure in USD for a market/side.
        
        Args:
            market_id: Market identifier
            side: 'YES' or 'NO'
            active_positions: Dict of positions
            
        Returns:
            Total USD exposure for this market/side
        """
        total_exposure = 0.0
        
        for pos_id, position in active_positions.items():
            if position.get('market_id') == market_id and position.get('side') == side:
                # Check if it's a whale position (tagged by gamma strategy)
                if position.get('strategy') in ['gamma_scalp', 'hft_gamma_scalp', 'whale']:
                    total_exposure += position.get('size', 0)
        
        return total_exposure
    
    def _evaluate_spread(
        self,
        market_id: str,
        token_id: str,
        side: str,
        best_bid: float,
        best_ask: float,
        bid_volume: float,
        ask_volume: float,
        spread_cents: float,
        position_size: float
    ) -> Optional[GammaOrder]:
        """
        Evaluate spread and determine order type.
        
        Gap vs. Wall Logic:
        - Gap (spread > 2 cents): Place limit bid inside the gap
        - Wall (spread <= 2 cents): Check depth, snipe or join
        
        Args:
            market_id: Market identifier
            token_id: CLOB token ID
            side: 'YES' or 'NO'
            best_bid: Best bid price
            best_ask: Best ask price
            bid_volume: Volume on bid side
            ask_volume: Volume on ask side
            spread_cents: Spread in absolute cents
            position_size: Size in USD
            
        Returns:
            GammaOrder or None
        """
        # Gap threshold: If spread > 2 cents, it's a "Gap"
        GAP_THRESHOLD = 0.02  # 2 cents
        
        # Wall crumbling threshold: Ask volume < 20% of bid volume
        WALL_CRUMBLE_RATIO = 0.2
        
        if spread_cents > GAP_THRESHOLD:
            # ============================================
            # SCENARIO A: THE GAP
            # ============================================
            # Wide spread - place limit bid inside the gap
            # Example: Bid $0.01 / Ask $0.04 → Place bid at $0.02
            
            # Calculate bid price: Midpoint between bid and ask, rounded down to nearest cent
            mid_price = (best_bid + best_ask) / 2
            bid_price = round(mid_price - 0.005, 2)  # Slightly below mid
            
            # Safety: Don't bid higher than ask - 1 cent
            bid_price = min(bid_price, best_ask - 0.01)
            
            # Safety: Don't bid lower than current best bid
            bid_price = max(bid_price, best_bid + 0.001)
            
            self.stats['gap_opportunities'] += 1
            
            return GammaOrder(
                market_id=market_id,
                token_id=token_id,
                side=side,
                order_type=GammaOrderType.LIMIT_BID,
                price=bid_price,
                size=position_size,
                reason=GammaOrderReason.GAP_OPPORTUNITY,
                best_bid=best_bid,
                best_ask=best_ask,
                bid_volume=bid_volume,
                ask_volume=ask_volume,
            )
        
        else:
            # ============================================
            # SCENARIO B: THE WALL
            # ============================================
            # Tight spread - check if wall is crumbling or strong
            
            if bid_volume > 0 and ask_volume < (bid_volume * WALL_CRUMBLE_RATIO):
                # Wall is crumbling! Snipe it (TAKER)
                # Ask volume is weak relative to bid volume
                
                self.stats['wall_snipes'] += 1
                
                return GammaOrder(
                    market_id=market_id,
                    token_id=token_id,
                    side=side,
                    order_type=GammaOrderType.MARKET_BUY,
                    price=best_ask,  # Expected fill price
                    size=position_size,
                    reason=GammaOrderReason.WALL_CRUMBLING,
                    best_bid=best_bid,
                    best_ask=best_ask,
                    bid_volume=bid_volume,
                    ask_volume=ask_volume,
                )
            
            else:
                # Wall is strong - join the bid (MAKER)
                
                self.stats['wall_joins'] += 1
                
                return GammaOrder(
                    market_id=market_id,
                    token_id=token_id,
                    side=side,
                    order_type=GammaOrderType.LIMIT_BID,
                    price=best_bid,  # Join at best bid
                    size=position_size,
                    reason=GammaOrderReason.WALL_STRONG,
                    best_bid=best_bid,
                    best_ask=best_ask,
                    bid_volume=bid_volume,
                    ask_volume=ask_volume,
                )
    
    # =========================================================================
    # EXIT LOGIC: check_exit_signals()
    # =========================================================================
    
    def check_exit_signals(
        self,
        active_positions: Dict[str, Dict],
        current_market_prices: Dict[str, Dict]
    ) -> List[GammaOrder]:
        """
        Check for exit signals on existing Whale positions.
        
        Implements "Free Roll" logic:
        - 2x Entry (Doubler): Sell 50% → recover initial investment
        - 5x Entry (Moonbag): Sell remaining 100% → maximize profit
        - 0.5x Entry (Stop Loss): Sell 100% → cut losses early
        
        Args:
            active_positions: Dict of position_id -> position data
            current_market_prices: Dict of market_id -> {best_bid, best_ask, yes_price, no_price}
            
        Returns:
            List of GammaOrder objects for exits
        """
        exit_orders = []
        
        for pos_id, position in active_positions.items():
            # Only process whale/gamma positions
            strategy = position.get('strategy', '')
            if strategy not in ['gamma_scalp', 'hft_gamma_scalp', 'whale', 'gamma']:
                continue
            
            market_id = position.get('market_id', '')
            side = position.get('side', 'YES')
            entry_price = position.get('entry_price', 0)
            current_size = position.get('size', 0)
            
            if entry_price <= 0 or current_size <= 0:
                continue
            
            # Get current market price
            market_prices = current_market_prices.get(market_id, {})
            current_bid = market_prices.get('best_bid', 0)
            
            if current_bid <= 0:
                # Try alternative price sources
                if side == 'YES':
                    current_bid = market_prices.get('yes_price', 0)
                else:
                    current_bid = market_prices.get('no_price', 0)
            
            if current_bid <= 0:
                continue
            
            # Calculate price multiple
            price_multiple = current_bid / entry_price
            
            # ===== EXIT CHECKS =====
            exit_order = self._check_exit_conditions(
                pos_id=pos_id,
                position=position,
                market_id=market_id,
                side=side,
                entry_price=entry_price,
                current_bid=current_bid,
                current_size=current_size,
                price_multiple=price_multiple,
                market_prices=market_prices
            )
            
            if exit_order:
                exit_orders.append(exit_order)
                logger.info(
                    f"🐋 [GAMMA EXIT] {market_id[:16]}... {exit_order.reason.value} | "
                    f"Entry: ${entry_price:.4f} → Current: ${current_bid:.4f} ({price_multiple:.1f}x) | "
                    f"Selling ${exit_order.size:.2f}"
                )
        
        return exit_orders
    
    def _check_exit_conditions(
        self,
        pos_id: str,
        position: Dict,
        market_id: str,
        side: str,
        entry_price: float,
        current_bid: float,
        current_size: float,
        price_multiple: float,
        market_prices: Dict
    ) -> Optional[GammaOrder]:
        """
        Check exit conditions for a single position.
        
        Exit ladder:
        1. FREE_ROLL (2x): Sell 50% to recover cost basis
        2. MOONBAG (5x): Sell 100% at huge profit
        3. STOP_LOSS (0.5x): Cut losses at 50% drawdown
        
        Args:
            Various position and market data
            
        Returns:
            GammaOrder for exit or None
        """
        token_id = position.get('token_id', '')
        
        # Check if we've already done a free roll
        free_roll_done = position.get('free_roll_done', False)
        
        # ===== THE MOONBAG (5x Entry) =====
        # Price has 5x'd - sell everything remaining
        if price_multiple >= 5.0:
            self.stats['moonbags'] += 1
            return GammaOrder(
                market_id=market_id,
                token_id=token_id,
                side=side,
                order_type=GammaOrderType.MARKET_SELL,
                price=current_bid,
                size=current_size,  # Sell 100%
                reason=GammaOrderReason.MOONBAG,
                entry_price=entry_price,
                position_id=pos_id,
                best_bid=current_bid,
                best_ask=market_prices.get('best_ask', current_bid + 0.01),
            )
        
        # ===== THE DOUBLER / FREE ROLL (2x Entry) =====
        # Price has doubled - sell 50% to recover initial investment
        if price_multiple >= 2.0 and not free_roll_done:
            self.stats['free_rolls'] += 1
            sell_size = current_size * 0.5  # Sell 50%
            return GammaOrder(
                market_id=market_id,
                token_id=token_id,
                side=side,
                order_type=GammaOrderType.MARKET_SELL,
                price=current_bid,
                size=sell_size,
                reason=GammaOrderReason.FREE_ROLL,
                entry_price=entry_price,
                position_id=pos_id,
                best_bid=current_bid,
                best_ask=market_prices.get('best_ask', current_bid + 0.01),
            )
        
        # ===== THE STOP LOSS (0.5x Entry) =====
        # Price has halved - cut losses
        if price_multiple <= 0.5:
            self.stats['stop_losses'] += 1
            return GammaOrder(
                market_id=market_id,
                token_id=token_id,
                side=side,
                order_type=GammaOrderType.MARKET_SELL,
                price=current_bid,
                size=current_size,  # Sell 100%
                reason=GammaOrderReason.STOP_LOSS,
                entry_price=entry_price,
                position_id=pos_id,
                best_bid=current_bid,
                best_ask=market_prices.get('best_ask', current_bid + 0.01),
            )
        
        return None
    
    # =========================================================================
    # UTILITY METHODS
    # =========================================================================
    
    def get_stats(self) -> Dict:
        """Get strategy statistics."""
        return {
            **self.stats,
            'config': {
                'whale_price_ceiling': self.config.WHALE_PRICE_CEILING,
                'whale_max_position': self.config.WHALE_MAX_POSITION,
                'whale_max_spread_cents': self.config.WHALE_MAX_SPREAD_CENTS,
            }
        }
    
    def reset_stats(self):
        """Reset statistics."""
        for key in self.stats:
            self.stats[key] = 0


# =============================================================================
# SINGLETON ACCESSOR
# =============================================================================

_gamma_trader: Optional[GammaTrader] = None

def get_gamma_trader() -> GammaTrader:
    """Get or create the singleton GammaTrader instance."""
    global _gamma_trader
    if _gamma_trader is None:
        _gamma_trader = GammaTrader()
    return _gamma_trader
